a, b = input().split()
plus = int(a)+int(b)
sub = int(a)-int(b)
multi = int(a)*int(b)
div = int(a)/int(b)
rest = int(a)%int(b)
print(plus)
print(sub)
print(multi)
print(int(div))
print(rest)
print(round(div,2))
